# Generated by Django 4.2.5 on 2023-10-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_public_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute_multi_option_values', to='product.optiongroupvalue', verbose_name='Value multi option'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_option_values', to='product.optiongroupvalue', verbose_name='Value option'),
        ),
    ]
