# Generated by Django 4.2.5 on 2023-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productattributevalue_value_multi_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='Value float'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value integer'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Value text'),
        ),
    ]
